fixtures/activity_feed/investment_projects/project_added_cti.json
fixtures/activity_feed/investment_projects/project_added_fdi.json
fixtures/activity_feed/investment_projects/project_added_non_fdi.json
fixtures/activity_feed/omis/order_added.json
src/activity-feed/__snapshots__/ActivityFeedCard.test.jsx.snap
src/activity-feed/activity-feed-cards/InvestmentProject.jsx
src/activity-feed/activity-feed-cards/Omis.jsx
src/activity-feed/activity-feed-cards/card/CardUtils.js

* New Order - (OMIS)
* Investment project - (FDI)
* Investment project - (Non-FDI)
* Investment project - (CTI)
https://trello.com/c/L1FIfGce/1308-add-contact-links-into-investment-projects-omis-orders

Add links to Data Hub company contacts

---

src/activity-feed/__snapshots__/ActivityFeed.test.jsx.snap
src/activity-feed/__snapshots__/ActivityFeedCard.test.jsx.snap
src/activity-feed/activity-feed-cards/InvestmentProject.jsx
src/activity-feed/activity-feed-cards/card/CardUtils.js

This change is consistent with both Interactions and OMIS activity feed cards.
https://trello.com/c/EepIKCfZ/1328-refactor-the-investment-projects-activity-feed-to-use-the-new-cardtable-component

Refactor Investment projects to use the new CardTable component

---

src/activity-feed/ActivityFeedHeader.jsx
src/activity-feed/__snapshots__/ActivityFeed.test.jsx.snap
src/activity-feed/__snapshots__/ActivityFeedCard.test.jsx.snap
src/activity-feed/__snapshots__/ActivityFeedHeader.test.jsx.snap
src/activity-feed/activity-feed-cards/Interaction.jsx
src/activity-feed/activity-feed-cards/InvestmentProject.jsx
src/activity-feed/activity-feed-cards/Omis.jsx
src/activity-feed/activity-feed-cards/card/Card.jsx
src/activity-feed/activity-feed-cards/card/CardDetails.jsx
src/activity-feed/activity-feed-cards/card/CardHeader.jsx
src/activity-feed/activity-feed-cards/card/CardHeading.jsx
src/activity-feed/activity-feed-cards/card/CardMeta.jsx
src/activity-feed/activity-feed-cards/card/index.js

Updates the CSS to be mobile first.

Update CSS to be mobile first

---

package.json
src/activity-feed/__snapshots__/ActivityFeed.test.jsx.snap
src/activity-feed/__snapshots__/ActivityFeedCard.test.jsx.snap
src/activity-feed/activity-feed-cards/InteractionUtils.js
src/activity-feed/activity-feed-cards/InteractionUtils.test.js
src/activity-feed/activity-feed-cards/card/CardMeta.jsx
yarn.lock

------------------------
Badges
------------------------
COMPLETE = GREEN_BORDER
UPCOMING = BLUE_BORDER
INCOMPLETE = BLUE_BORDER
CANCELLED = RED_BORDER
COMPLETED_SERVICE_DELIVERY = RED_BORDER
https://trello.com/c/7z7F8Vd4/1296-update-badge-colour-based-upon-status-ie-cancelled-interaction-is-red

Add coloured badge borders

---

.circleci/config.yml
src/activity-feed/ActivityFeed.stories.jsx
src/activity-feed/ActivityFeed.test.jsx
src/activity-feed/ActivityFeedCard.jsx
src/activity-feed/__snapshots__/ActivityFeed.test.jsx.snap
src/activity-feed/activity-feed-cards/Default.jsx
src/activity-feed/activity-feed-cards/Interaction.jsx
src/activity-feed/activity-feed-cards/InvestmentProject.jsx
src/activity-feed/activity-feed-cards/Omis.jsx
src/activity-feed/activity-feed-cards/card/Card.jsx
src/activity-feed/activity-feed-cards/card/CardDetails.jsx
src/activity-feed/activity-feed-cards/card/CardHeader.jsx
src/activity-feed/activity-feed-cards/card/CardHeading.jsx
src/activity-feed/activity-feed-cards/card/CardHeadingBlock.jsx
src/activity-feed/activity-feed-cards/card/CardMeta.jsx
src/activity-feed/activity-feed-cards/card/CardTable.jsx

https://trello.com/c/LSCn0Yvf/1295-stress-test-activity-feed-performance-with-high-numbers-of-interactions

Improve rendering performance of the activity feed

---

package.json
yarn.lock

Available here: https://uktrade.github.io/data-hub-components

Publish storybook to GitHub Pages after each release

---

.storybook/config.js
src/activity-feed/__snapshots__/ActivityFeed.test.jsx.snap
src/activity-feed/__snapshots__/ActivityFeedCard.test.jsx.snap
src/activity-feed/activity-feed-cards/card/CardDetails.jsx
src/activity-feed/activity-feed-cards/card/CardHeading.jsx
src/activity-feed/activity-feed-cards/card/CardMeta.jsx
src/activity-feed/activity-feed-cards/card/CardTable.jsx

Updates the global font sizes to be consistent with GDS design system. The activity card should be consistent with existing collection cards.

Update font size to be consistent

---

src/activity-feed/activity-feed-cards/card/CardDetails.jsx

fix: Use font size constant on card details

---

commitlint.config.js
package.json
yarn.lock

Block commits if the commit message is not compliant with semantic release conventions.

chore: Lint commit message with git hook

---

fixtures/activity_feed/companies_house/accounts_are_due.json
fixtures/activity_feed/companies_house/incorporated.json
fixtures/activity_feed/hmrc/export_of_goods.json
fixtures/activity_feed/index.js
src/activity-feed/ActivityFeedCard.test.jsx
src/activity-feed/__snapshots__/ActivityFeed.test.jsx.snap
src/activity-feed/__snapshots__/ActivityFeedCard.test.jsx.snap
src/activity-feed/activity-feed-cards/CompaniesHouseAccount.jsx
src/activity-feed/activity-feed-cards/CompaniesHouseCompany.jsx
src/activity-feed/activity-feed-cards/HmrcExporter.jsx
src/activity-feed/activity-feed-cards/card/CardDetails.jsx
src/activity-feed/activity-feed-cards/card/CardDetails.test.jsx
src/activity-feed/activity-feed-cards/card/CardDetailsList.jsx
src/activity-feed/activity-feed-cards/card/CardHeading.jsx
src/activity-feed/activity-feed-cards/card/CardHeading.test.jsx
src/activity-feed/activity-feed-cards/card/CardHeadingBlock.jsx
src/activity-feed/activity-feed-cards/card/__snapshots__/CardDetails.test.jsx.snap
src/activity-feed/activity-feed-cards/card/__snapshots__/CardHeading.test.jsx.snap
src/activity-feed/activity-feed-cards/card/item-renderers/BooleanItemRenderer.jsx
src/activity-feed/activity-feed-cards/card/item-renderers/DefaultItemRenderer.jsx
src/activity-feed/activity-feed-cards/card/item-renderers/index.js
src/activity-feed/activity-feed-cards/index.js
src/activity-feed/constants.js

Create external sources activity cards for Companies House Accounts, Companies House Companies and HMRC Exporters data. Update styling to match latest design.

feat: Create external sources activity cards

---

package.json
src/entity-search/EntityFilter.jsx
src/entity-search/EntityFilterRow.jsx
src/entity-search/EntityFilters.jsx
src/entity-search/EntitySearch.jsx
src/entity-search/EntitySearch.stories.jsx
src/entity-search/EntitySearch.test.jsx
src/entity-search/EntitySearchWithDataProvider.jsx
src/entity-search/__snapshots__/EntitySearch.test.jsx.snap
src/entity-search/data-providers/DnbCompanySearch.js
src/entity-search/fixtures/company-search-postcode-BN1-4SE.json
src/entity-search/fixtures/company-search-some-other-company.json
src/entity-search/useFilter.js
src/entity-search/useFilter.test.js
yarn.lock

Change adds filters to the entity search. Each filter is appended as a parameter in the query string on the endpoint.

feat: Introduce entity filters

---

src/entity-search/CannotFindDetails.jsx
src/entity-search/EntityFilterRow.jsx
src/entity-search/EntityList.jsx
src/entity-search/EntitySearch.stories.jsx
src/entity-search/__snapshots__/EntitySearch.test.jsx.snap

Updates styles to be aligned with design. Feedback was received from designers and applied.
Includes:
- increased spacing between filters and search results
- updated font sizes for search results

Update entity search component styles

---

src/entity-search/EntitySearch.stories.jsx
src/entity-search/EntitySearch.test.jsx
src/entity-search/fixtures/index.js

refactor: Organise entity search fixtures

---

src/entity-search/EntitySearch.jsx
src/entity-search/EntitySearch.stories.jsx
src/entity-search/EntitySearch.test.jsx
src/entity-search/EntitySearchWithDataProvider.jsx
src/entity-search/__snapshots__/EntitySearch.test.jsx.snap

If there is an error when requesting the endpoint then we want to correctly handle that and display a friendly message to the user.
1. Go to `/?path=/story/entitysearch--data-hub-company-search-with-server-error`
2. Click `Search`, you should be presented with an error

Display error message for server error in entity search component

---

src/entity-search/EntitySearch.stories.jsx

Refactors stories to be more concise.

refactor: Remove repetition for stories

---

src/dashboard/my-companies/MyCompaniesTile.jsx
src/dashboard/my-companies/MyCompaniesTile.test.jsx

This fixes the "no companies in your search" from appearing incorrectly in the "my companies" tile.

fix: filter text message conditional

---

src/entity-search/EntityFilter.jsx
src/entity-search/EntityFilters.jsx
src/entity-search/EntitySearch.jsx
src/entity-search/EntitySearch.stories.jsx
src/entity-search/EntitySearch.test.jsx
src/entity-search/__snapshots__/EntitySearch.test.jsx.snap

If a field is optional then it needs to be presented with the label.

fix: Add (optional) to optional fields

---

src/entity-search/EntitySearch.test.jsx
src/entity-search/__snapshots__/EntitySearch.test.jsx.snap

`EntitySearch.test.jsx` file was deleted by mistake in #123, this PR is bringing this file back.

test: Recover previously deleted EntitySearch.test.jsx

---

package.json
src/forms/elements/FieldSelect.jsx
src/forms/elements/__stories__/FieldSelect.stories.jsx
src/forms/elements/__stories__/Form.stories.jsx
src/forms/elements/__tests__/FieldSelect.test.jsx
yarn.lock

feat: Add FieldSelect to forms

---

src/index.jsx

These are missing and useful for consuming the library.

feat: Add default exports for components

---

package.json
src/forms/hooks/__tests__/useForm.test.jsx
src/forms/hooks/useForm.js
yarn.lock

Prevent users from accidental loss of data when reloading form which wasn't submitted.
https://trello.com/c/00net3J8/278-show-alert-when-user-leaves-the-form-which-is-in-progress

feat: Show alert when leaving unsaved form

---

.circleci/config.yml

Fixes random failures of our tests due to lack of memory in CirrcleCI.
Related CI job: https://circleci.com/gh/uktrade/data-hub-components/1220

ci: Lower the memory usage of Jest tests

---

src/entity-search/__fixtures__/company-search.json
src/entity-search/__tests__/__snapshots__/useDnbSearch.test.jsx.snap
src/entity-search/__tests__/useDnbSearch.test.jsx
src/entity-search/useDnbSearch.jsx
src/forms/elements/__tests__/FieldDnbCompany.test.jsx

https://trello.com/c/fcuZ7lDX/338-indicate-dissolved-companies-on-the-dnb-company-search-results

feat: Indicate dissolved companies in DnB search results

---

src/forms/hooks/__tests__/useForm.test.jsx
src/forms/hooks/useForm.js

Add form state as a third argument to the field validators to allow cross-field validation, e.g.
```
function validateWebsiteOrPhone (value, name, formState) {
const { website, telephone_number } = formState.values
return !website && !telephone_number ? 'Enter at least a website or a phone number' : null
}
<FieldInput
label="Company's website"
name="website"
type="url"
validate={validateWebsiteOrPhone}
/>
<FieldInput
label="Company's telephone number"
name="telephone_number"
type="tel"
validate={validateWebsiteOrPhone}
/>
```

feat: Let field validators access form state

---

src/forms/elements/FieldAddress.jsx
src/forms/elements/__stories__/FieldAddress.stories.jsx

Sets the country field value as the country ID.

fix: Set country as country ID

---

src/forms/elements/FieldAddress.jsx

fix: Set country.id rather than address.country.id

---

src/entity-search/EntityListItem.jsx
src/entity-search/__tests__/EntityList.test.jsx
src/entity-search/__tests__/EntityListItem.test.jsx
src/forms/elements/__tests__/Step.test.jsx

This change will let users tab through entity search results.

fix: Make EntityListItem focusable

---

src/forms/elements/FieldCheckboxes.jsx
src/forms/elements/FieldDnbCompany.jsx
src/forms/elements/FieldInput.jsx
src/forms/elements/FieldSelect.jsx
src/forms/elements/FieldUneditable.jsx
src/forms/elements/FieldWrapper.jsx
src/forms/elements/__stories__/FieldCheckboxes.stories.jsx
src/forms/elements/__tests__/FieldCheckboxes.test.jsx
src/forms/elements/__tests__/FieldSelect.test.jsx

Add new field type for checkboxes.

feat: Add FieldCheckboxes

---

src/address-search/AddressSearch.jsx
src/address-search/__mocks__/postcode-lookup.js
src/address-search/__tests__/AddressSearch.test.jsx
src/address-search/__tests__/PostcodeLookup.test.js
src/address-search/__tests__/useAddressSearch.test.js
src/forms/elements/__stories__/FieldAddress.stories.jsx
src/forms/elements/__tests__/FieldDnbCompany.test.jsx

Unit tests for Postcode lookup.

test: add Postcode lookup/ Address search unit tests

---

src/collection-list/CollectionItem.jsx
src/collection-list/__fixtures__/index.js
src/collection-list/__fixtures__/interactionItem.json
src/collection-list/__fixtures__/largeCapitalProfileItem.json
src/collection-list/__stories__/CollectionList.stories.jsx
src/collection-list/__tests__/CollectionItem.test.jsx
src/collection-list/items/Item.jsx
src/collection-list/items/ItemBadge.jsx
src/collection-list/items/ItemBadgeWrapper.jsx
src/collection-list/items/ItemMeta.jsx
src/collection-list/items/ItemMetaWrapper.jsx
src/collection-list/items/__tests__/Item.test.jsx
src/collection-list/items/__tests__/ItemBadge.test.jsx
src/collection-list/items/__tests__/ItemBadgeWrapper.test.jsx
src/collection-list/items/__tests__/ItemUpdatedDate.test.jsx
src/collection-list/items/__tests__/ItemUpdatedDateContainer.test.jsx
src/collection-list/items/index.js

Add `CollectionItem` component.
This is the start of a large piece of work to build out the CollectionList template in React in order to show a list of Large Capital Profiles. 
The aim is to get to something resembling the below screenshot:

feat: Add "CollectionItem" component

---

scripts/setupTests.js
src/company-lists/AddRemoveFromListForm.jsx
src/company-lists/CreateListForm.jsx
src/company-lists/__stories__/CompanyLists.stories.jsx
src/company-lists/__stories__/DeleteCompanyListSection.stories.jsx
src/company-lists/__tests__/AddRemoveFromList.test.jsx
src/company-lists/__tests__/CreateListForm.test.jsx
src/forms/elements/FieldAddress.jsx
src/forms/elements/FieldDnbCompany.jsx
src/forms/elements/Form.jsx
src/forms/elements/__stories__/Form.stories.jsx
src/forms/elements/__tests__/FieldInput.test.jsx
src/forms/elements/__tests__/Form.test.jsx
src/forms/elements/__tests__/Step.test.jsx
src/forms/hooks/__tests__/useForm.test.jsx
src/forms/hooks/useForm.js

This PR includes only API changes.
From now on, redirections, form loading state and error state will now be handled internally, so there is no need for using `LoadingBox` or calling `window.location.href`.
Before:
```
function AddCompanyForm () {
const [isSubmitting, setIsSubmitting] = useState(false)
const onSubmit = async (values) => {
setIsSubmitting(true)
try {
const { data } = await axios.post('/create-company', values)
window.location.href = `/companies/${data.id}`
} catch (error) {
// todo handle error
setIsSubmitting(false)
}
}
return (
<Form onSubmit={onSubmit}>
<LoadingBox loading={isSubmitting}>
<FieldInput label="Name" type="text" />
</LoadingBox>
</Form>
)
}
```
After:
```
function AddCompanyForm () {
const onSubmit = async (values) => {
const { data } = await …
```

Improve form state handling during loading and when errors occur

---

src/collection-list/CollectionItem.jsx
src/collection-list/CollectionList.jsx
src/collection-list/CollectionPagination.jsx
src/collection-list/__fixtures__/capitalProfileCollectionList1.json
src/collection-list/__fixtures__/index.js
src/collection-list/__fixtures__/paginationProps.json
src/collection-list/__stories__/CollectionList.stories.jsx
src/collection-list/__tests__/CollectionList.test.jsx
src/collection-list/__tests__/CollectionPagination.test.jsx
src/collection-list/getNumberParam.js
src/collection-list/index.js
src/collection-list/truncatePages.js

The component can receive minimum number of props and infer the others it needs. 
Tests  updated to match. 
Logic for truncation is now within the component itself. This logic is largely based on the existing logic in the frontend repo. Welcome suggestions on how to simplify it.

refactor: refactor CollectionPagination

---

src/dashboard/my-companies/MyCompaniesTable.jsx

This sets fixed percentage widths on the table cells and removes the centre alignment on the "Last interaction" cells.

fix: company lists width size and cell alignment

---

src/index.jsx

Export CollectionList from `index.jsx`

feat/export CollectionList

---

src/activity-feed/ActivityFeed.jsx
src/activity-feed/ActivityFeedApp.jsx
src/activity-feed/__stories__/ActivityFeed.stories.jsx
src/activity-feed/__tests__/ActivityFeed.test.jsx
src/activity-feed/constants.js
src/activity-feed/filters/__tests__/BasicActivityTypeFilter.test.jsx

deactivate activity type filter

refactor: deactivate activity type filter

---

src/badge/Badge.jsx
src/badge/__stories__/Badge.stories.jsx
src/badge/__tests__/Badge.test.jsx
src/index.jsx

It will be used on the activity feed and on the collection pages.

feat: Add Badge component

---

src/summary-table/SummaryTable.jsx
src/summary-table/__stories__/SummaryTable.stories.jsx
src/summary-table/__tests__/SummaryTable.test.jsx

Add new component used on the company details page and a few other pages.

feat: Add SummaryTable component

---

src/new-window-link/NewWindowLink.jsx
src/new-window-link/__stories__/NewWindowLink.stories.jsx
src/new-window-link/__tests__/NewWindowLink.test.jsx

Small component used to mark links which opens in a new window.

feat: Add NewWindowLink component

---

src/index.jsx
src/summary-table/SummaryTable.jsx

Export components which were omitted in previous PRs.

fix: Export missing components

---

src/utils/DateUtils.js
src/utils/__tests__/DateUtils.test.js

Added a simple helper function that will take a date and time such as: `2019-12-10T18:12:37.649476Z` and format it to: `10 Dec 2019, 6:12pm`

feat: Add a static function - formattedDateAndTime

---

src/activity-feed/activities/CompaniesHouseAccount.jsx
src/activity-feed/activities/InvestmentProject.jsx
src/utils/NumberUtils.js
src/utils/__tests__/NumberUtils.test.js

Added a USD currency formatter.

feat: Add USD currency formatter

---

src/metadata/Metadata.jsx
src/summary-list/SummaryList.jsx
src/summary-list/__stories__/SummaryList.stories.jsx
src/summary-list/__tests__/SummaryList.test.jsx

Add SummaryList component

---

src/collection-list/CollectionItem.jsx
src/collection-list/__stories__/CollectionItem.stories.jsx
src/collection-list/__tests__/CollectionItem.test.jsx

feat: Show an H3 header if no link is passed to the collectionItem

---

src/activity-feed/__tests__/ActivityFeedApp.test.jsx
src/forms/elements/__stories__/Form.stories.jsx
src/forms/elements/__tests__/FieldAddress.test.jsx
src/forms/elements/__tests__/FieldDnbCompany.test.jsx
src/forms/hooks/__tests__/useForm.test.jsx
src/forms/hooks/useForm.js
src/utils/enzyme.js

fix: Do not show prompt when form is redirected after submission

---

src/forms/elements/FieldDnbCompany.jsx

fix: Search results status message content change

---

src/pagination/__tests__/Pagination.test.jsx
src/pagination/computeVisiblePieces.js

fix: Hide ellipsis when there are 5 of total pages

---

src/forms/elements/FieldDnbCompany.jsx
src/forms/elements/__tests__/FieldDnbCompany.test.jsx

Content updates to the D&B company search.

fix: Update the content within FieldDnbCompany

---

src/forms/elements/FieldDnbCompany.jsx
src/forms/elements/__tests__/FieldDnbCompany.test.jsx

feat: Make the message above DNB search results customisable via prop

---

package.json

Which will allow for review apps in component lib:
https://data-hub-com-configurab-uovuzw.herokuapp.com/

ci: Allow to configure storybook port (for heroku review apps)

---

src/activity-feed/__fixtures__/index.js
src/activity-feed/__fixtures__/referrals/completeReferral.json
src/activity-feed/__fixtures__/referrals/outstandingReferral.json
src/activity-feed/__stories__/ActivityFeed.stories.jsx
src/activity-feed/__tests__/Activity.test.jsx
src/activity-feed/__tests__/__snapshots__/Activity.test.jsx.snap
src/activity-feed/activities/InteractionUtils.js
src/activity-feed/activities/Referral.jsx
src/activity-feed/activities/ReferralUtils.js
src/activity-feed/activities/__tests__/ReferralUtils.test.js
src/activity-feed/activities/card/CardUtils.jsx
src/activity-feed/activities/card/__tests__/CardUtils.test.js
src/activity-feed/activities/index.js
src/activity-feed/constants.js

Trello - https://trello.com/c/L0XaqC5U/1080-fe-show-referrals-on-activity-feed-5
We need to add the completed and outstanding referrals to the Activity feed.

Add referrals to activity feed

---

src/status-message/StatusMessage.jsx

Reverts uktrade/data-hub-components#269
I'm reverting this because the component library accidentally let through a commit without a keyword in it, so it won't release. I will re-create it properly after this change is approved

Revert "refactor: Change the way StatusMessage returns"

---

package.json
src/forms/elements/FieldTextarea.jsx
src/forms/elements/__stories__/FieldTextarea.stories.jsx
src/forms/elements/__tests__/FieldTextarea.test.jsx
src/index.jsx

Add field wrapper for `textarea` element so it can be used in forms.

feat: Add FieldTextarea

---

src/status-message/StatusMessage.jsx

Re-creating this PR (again as the branch was being silly) but doing the commits properly this time - for context when I created this originally the commit message didn't contain a keyword so didn't release properly. For more context of why I am making this change please see the old PR.

refactor: Change the way that StatusMessage returns (again)

---

src/activity-feed/__tests__/__snapshots__/Activity.test.jsx.snap
src/activity-feed/activities/Referral.jsx
src/activity-feed/activities/ReferralUtils.js
src/activity-feed/activities/__tests__/ReferralUtils.test.js
src/activity-feed/activities/card/CardUtils.jsx
src/activity-feed/activities/card/__tests__/CardUtils.test.js

Small update to fix the links of referrals in the activity feed.

Fix referral urls in activity feed

---

src/forms/elements/FieldRadios.jsx
src/forms/elements/FieldWrapper.jsx
src/forms/elements/__stories__/FieldRadios.stories.jsx
src/forms/elements/__tests__/FieldRadios.test.jsx

Add new prop to the `FieldRadios` to render radios inline.

feat: Add inline prop to FieldRadios

---

src/activity-feed/__tests__/__snapshots__/Activity.test.jsx.snap
src/activity-feed/activities/Referral.jsx
src/activity-feed/activities/card/CardDetailsList.jsx
src/activity-feed/activities/card/CardTable.jsx

The cards table content(headers) in the activity feed are all miss-aligned. As the structure slightly differs between a referral and interaction I have now set a minimum width for both referral and interactions so they align correctly.

Align the table headers in all activity feed cards

---

src/forms/elements/FieldCheckboxes.jsx
src/forms/elements/FieldDate.jsx
src/forms/elements/FieldInput.jsx
src/forms/elements/FieldRadios.jsx
src/forms/elements/FieldSelect.jsx
src/forms/elements/FieldTextarea.jsx
src/forms/elements/FieldTypeahead.jsx
src/forms/elements/Step.jsx
src/forms/elements/__stories__/FieldTypeahead.stories.jsx

Let set initial value of form field using prop, e.g.
```
<FieldInput name="Age" initialValue="29" />
```

feat: Add initialValue prop to form fields

---

src/forms/elements/FieldDnbCompany.jsx
src/forms/elements/__tests__/FieldDnbCompany.test.jsx

Update content of two error messages when searching for a D&B company
https://trello.com/c/wH5jLg9K/1052-rewrite-error-message-in-the-matching-companies-journey

feat: Update content of error messages on D&B company search

---

src/forms/elements/FieldSelect.jsx
src/forms/elements/__stories__/FieldSelect.stories.jsx
src/forms/elements/__tests__/FieldSelect.test.jsx

Use the `value` instead of `defaultValue`
https://reactjs.org/docs/forms.html#the-select-tag

fix: correctly select a <select> option
