package.json
src/activity-feed/ActivityFeedHeader.jsx
src/activity-feed/ActivityFeedHeader.test.jsx
src/activity-feed/__snapshots__/ActivityFeed.test.jsx.snap
src/activity-feed/__snapshots__/ActivityFeedHeader.test.jsx.snap
yarn.lock

https://trello.com/c/ZVZurdkL/1327-display-1-activity-instead-of-1-activities-in-the-activity-feed

Display "1 activity" instead of "1 activities" in the activity feed header

---

src/activity-feed/__snapshots__/ActivityFeedCard.test.jsx.snap
src/activity-feed/activity-feed-cards/Interaction.jsx
src/activity-feed/activity-feed-cards/InteractionUtils.js
src/activity-feed/activity-feed-cards/InteractionUtils.test.js

Currently service deliveries are using "Completed interaction" but they should be using "Completed
service delivery"
Link text with `interaction` should use `service delivery` for service deliveries.

Update service delivery card to be more specific

---

fixtures/activity_feed/interactions/service_delivery.json
src/activity-feed/__snapshots__/ActivityFeed.test.jsx.snap
src/activity-feed/__snapshots__/ActivityFeedCard.test.jsx.snap
src/activity-feed/activity-feed-cards/InteractionUtils.js
src/activity-feed/activity-feed-cards/InteractionUtils.test.js

Updates badge text for completed interactions and service deliveries to be simply `Interaction` and `Service delivery`.

Update interaction and service delivery completed badge text

---

src/activity-feed/ActivityFeed.jsx
src/activity-feed/ActivityFeed.test.jsx
src/activity-feed/ActivityFeedCard.jsx
src/activity-feed/ActivityFeedCard.test.jsx
src/activity-feed/ActivityFeedFilters.jsx
src/activity-feed/ActivityFeedFilters.test.jsx
src/activity-feed/__snapshots__/ActivityFeed.test.jsx.snap
src/activity-feed/__snapshots__/ActivityFeedFilters.test.jsx.snap
src/activity-feed/activity-feed-cards/Interaction.jsx
src/activity-feed/activity-feed-cards/InvestmentProject.jsx
src/activity-feed/activity-feed-cards/Omis.jsx
src/activity-feed/activity-feed-cards/card/CardDetails.jsx
src/activity-feed/activity-feed-cards/card/CardDetails.test.jsx
src/activity-feed/activity-feed-cards/card/__snapshots__/CardDetails.test.jsx.snap

Clicking the link will show details for all activities. The text will become "Hide details for all activities". Clicking the link again will return it to its original state with all details hidden.

Add "Show details for all activities" toggle

---

.dependabot/config.yml

Remove noise and allow only for security updates.

ci: Use dependabot only for security updates

---

package.json

Add `--debug` option to the `semantic-release` command so we have a better understanding what's going on.

ci: Add debug option to semantic-release

---

package.json

Add `--quiet` argument to the `build-storybook` so the console output in CircleCI is still readable.
Example build with unreadable output: https://circleci.com/gh/uktrade/data-hub-components/601

ci: Hide output of the build-storybook command

---

src/entity-search/CannotFindDetails.jsx
src/entity-search/EntitySearch.jsx
src/entity-search/EntitySearch.stories.jsx
src/entity-search/EntitySearch.test.jsx
src/entity-search/__snapshots__/EntitySearch.test.jsx.snap

Adds the "cannot find" footer for when the user cannot find the entity they are looking for. The footer guides them through correcting the problem.

feat: Add entity search cannot find footer

---

.circleci/config.yml

There is no need to run CI on our storybook branch.
Example failing task: https://circleci.com/gh/uktrade/data-hub-components/697

ci: Add `gh-pages` to ignored branches in CircleCI

---

src/activity-feed/activity-feed-cards/CompaniesHouseAccount.jsx
src/activity-feed/activity-feed-cards/CompaniesHouseCompany.jsx
src/activity-feed/activity-feed-cards/HmrcExporter.jsx

A date was being formatted twice which moment does not like and will not support in the future.

refactor: Remove moment warning

---

src/entity-search/EntityList.jsx

Missing prop type definition for `entities`.

refactor: Define prop type for entities

---

src/activity-feed/__snapshots__/ActivityFeed.test.jsx.snap
src/activity-feed/__snapshots__/ActivityFeedCard.test.jsx.snap
src/activity-feed/activity-feed-cards/card/Card.jsx

Activity feed was using an arbitrary grey `#c0c0c0`. This change reuses the `GREY` from `govuk-colours`.
Check the borders at `/?path=/story/activityfeed--data-hub-company-page`
The visual difference is subtle as the previous value was not specified by GDS.

refactor: Reuse grey constant from govuk-colours

---

src/entity-search/CannotFindDetails.jsx
src/entity-search/EntitySearch.jsx
src/entity-search/EntitySearch.stories.jsx
src/entity-search/EntitySearch.test.jsx
src/entity-search/PreviouslySelected.jsx
src/entity-search/__snapshots__/EntitySearch.test.jsx.snap

Adds a `PreviouslySelected` component to `EntitySearch`. If `previouslySelected` is specified then the component is rendered. This is ideal for when the entity search is part of a multi step process. The user may select a country first and then decide they want to change when using the entity search. They will be able to click the `Change` link to update the country selected.
Browse to `~/?path=/story/entitysearch--data-hub-company-search-with-previously-selected-value-and-change-link`

feat: Add previously selected component

---

src/entity-search/EntityList.jsx
src/entity-search/EntitySearch.jsx
src/entity-search/EntitySearch.stories.jsx
src/entity-search/EntitySearch.test.jsx
src/entity-search/__snapshots__/EntitySearch.test.jsx.snap

Adds the entity search result click event to the entity search component.
1. Browse to `/?path=/story/entitysearch--data-hub-company-search`
2. Click `Search`
3. Click a search result. You should see an `alert`.
There should be no visual change although in Storybook the click event will `alert` the entity as a string.

Add search result onClick event to entity search component

---

src/entity-search/EntityList.jsx
src/entity-search/EntitySearch.jsx
src/entity-search/EntitySearch.stories.jsx
src/entity-search/EntitySearch.test.jsx
src/entity-search/EntitySearchWithDataProvider.jsx
src/entity-search/__snapshots__/EntitySearch.test.jsx.snap
src/entity-search/fixtures/company-search-no-results.json
src/entity-search/fixtures/index.js

When no entities are returned from the API request, a friendly message should be presented to the user rather than nothing at all.
1. Browse to `/?path=/story/entitysearch--data-hub-company-search-with-no-results`
2. Click `Search`. You should see `There are no entities to show.`

feat: Show message when no entities returned

---

src/entity-search/EntityList.jsx
src/entity-search/EntityListItem.jsx
src/entity-search/EntityListItemMetaList.jsx
src/entity-search/EntitySearch.stories.jsx
src/entity-search/EntitySearch.test.jsx
src/entity-search/__snapshots__/EntitySearch.test.jsx.snap
src/entity-search/data-providers/DnbCompanySearch.jsx

For some entities we may want to display some inset text and therefore handle click events in a different way.
An example of this is for companies that are known by DIT. We will display a message containing a link so that the user can browse to the company page and add activity. In this case the entity click event should be ignored. When the company is not known by DIT then the entity click event is handled to move to the next stage of the process for adding a company.
1. Browse to `/?path=/story/entitysearch--data-hub-company-search`
2. Click the first entity and the click event is ignored. Click the `Go to the company page` link the URL will change
3. Click the second entity and the click event is handled with an `alert`

Present text when entity is known, handle click event differently

---

fixtures/activity_feed/companies_house/accounts_are_due.json
fixtures/activity_feed/companies_house/incorporated.json
fixtures/activity_feed/hmrc/export_of_goods.json
src/activity-feed/activity-feed-cards/CompaniesHouseAccount.jsx
src/activity-feed/activity-feed-cards/CompaniesHouseCompany.jsx
src/activity-feed/activity-feed-cards/HmrcExporter.jsx

fix: Change external sources cards to use startTime instead of published such that they will be sorted by date in the rendered feed

fix: Change external sources cards to use startTime instead of published

---

src/entity-search/EntitySearch.jsx
src/entity-search/EntitySearch.test.jsx
src/entity-search/__snapshots__/EntitySearch.test.jsx.snap

When clicking the "Search" button, the default event should not be fired. An example of this is when the entity component is within a step of a multi step form, and the form should not be submitted.

fix: Fix "Search" button firing default event

---

package.json
src/entity-search/EntitySearch.stories.jsx
src/entity-search/EntitySearch.test.jsx
src/entity-search/data-providers/DnbCompanySearch.jsx
yarn.lock

Rather than appending a query string, this change will mean that the filters will be in the body of the `POST` request.
The rationale for doing this is that it is uncommon to use the query string to `POST` data to the server and this is normally done by sending it in the body after the headers. This will make the request consistent with what is expected by the existing backend API endpoint. In addition this was becoming difficult to manage as the CSRF token was also being appended to the query string.

feat: POST object rather than query params

---

src/entity-search/EntityList.jsx
src/entity-search/EntitySearch.jsx
src/entity-search/__snapshots__/EntitySearch.test.jsx.snap

When there are large amounts of results the search button is difficult to find. The button is now in a more logical location.

feat: Move "Search" button above results

---

package.json

There is an CircleCI setting to ignore `gh-pages` branch but it's not taken into account as it's not deployed. This PR is fixing that.

build: Add gh-pages to ignored branches in CircleCI config

---

src/activity-feed/ActivityFeed.test.jsx

This is a performance tests and should be handled separately, 
For instance, `ActivityFeed.perf.js` could make use of the  `benchmark.js` library.

test: Remove redundant tests in Activity Feed

---

src/entity-search/EntitySearch.stories.jsx
src/entity-search/EntitySearch.test.jsx
src/entity-search/__snapshots__/EntitySearch.test.jsx.snap

This is a pass through to the API and the name is different to what is expected. The parameter for filtering by postcode is `postal_code` and not `address_postcode`.

fix: Change address_postcode key to postal_code

---

src/forms/core/__tests__/useForm.test.jsx
src/forms/core/useForm.js
src/forms/elements/__tests__/FieldError.test.jsx

Let users define more than one validator in fields.
Before:
```
<FieldInput
type="text"
name="name"
label="Name"
validate={value => (!value ? 'name is required' : null)}
/>
```
After:
```
<FieldInput
type="text"
name="name"
label="Name"
validate=[
validateRequired,
validateName,
]
/>
```

feat: Support multiple validators in forms field

---

src/entity-search/CannotFindDetails.jsx
src/entity-search/__snapshots__/EntitySearch.test.jsx.snap

Change adds explicit styles to the actions list so that these are not reset by consumers.
There should be no visual difference.

fix: Update cannot find action list styles

---

src/forms/elements/FieldDnbCompany.jsx
src/forms/elements/__stories__/FieldDnbCompany.stories.jsx
src/forms/elements/__tests__/FieldDnbCompany.test.jsx

Adds the element `FieldDnbCompany` so that a component which searches and selects D&B companies is as follows:
```html
<FieldDnbCompany
name="dnb_company"
label="Find the company"
country={values.companyLocation}
apiEndpoint={API_ENDPOINT}
/>
```
An example of this element can be viewed on the second step of Storybook at `~/?path=/story/forms--multistep-add-d-b-company-form`.

Add Field D&B company

---

src/forms/elements/FieldInput.jsx
src/forms/elements/FieldRadios.jsx
src/forms/elements/FieldSelect.jsx
src/forms/elements/__stories__/FieldSelect.stories.jsx
src/forms/elements/__stories__/Form.stories.jsx
src/forms/hooks/__tests__/useField.test.jsx
src/forms/hooks/useField.js

Old API:
```
<FieldSelect
name="country"
label="Country"
validate={value => (!value ? 'Chose one of the countries' : null)}
options={[
{ label: 'Germany', value: 'de' },
{ label: 'France', value: 'fr' },
{ label: 'Italy', value: 'it' },
]}
/>
```
New API:
```
<FieldSelect
name="country"
label="Country"
required="Chose one of the countries"
options={[
{ label: 'Germany', value: 'de' },
{ label: 'France', value: 'fr' },
{ label: 'Italy', value: 'it' },
]}
/>
```

feat: Add "required" prop to form fields to simplify validation

---

src/entity-search/EntitySearch.jsx
src/entity-search/__stories__/EntitySearch.stories.jsx
src/entity-search/__tests__/EntitySearch.test.jsx
src/forms/elements/FieldDnbCompany.jsx
src/forms/elements/__tests__/FieldDnbCompany.test.jsx
src/index.jsx
src/status-message/StatusMessage.jsx
src/status-message/StatusMessageVariant.js
src/status-message/__stories__/StatusMessage.stories.jsx
src/status-message/__tests__/StatusMessage.test.jsx

This change introduces a status message component. This is a common pattern used across Data Hub. In this particular instance it is required for displaying information at the top of the entity search component.
This change includes:
- `StatusMessage` component
- integrating component with existing entity search
- integrating component with `FieldDnbCompany`
Browse to any:
- `/?path=/story/statusmessage--default`
- `/?path=/story/statusmessage--custom-colour`
- `/?path=/story/entitysearch--data-hub-company-search-with-entity-list-header`, click 
- `/?path=/story/forms--fielddnbcompany-default`, click `Search`

Add StatusMessage to EntitySearch

---

src/entity-search/CannotFindDetails.jsx
src/entity-search/__stories__/EntitySearch.stories.jsx
src/forms/elements/FieldDnbCompany.jsx

Based upon user feedback, he `CannotFindDetails` section after the search results is being updated so that the information is easier to understand.
1. Browse to Storybook
2. Browse to `FieldDnbCompany`
3. Click "Search"
4. Click "I cannot find the company I am looking for", the updated wording should be presented

fix: Update cannot find words based on feedback

---

package.json

There is no need to include development related directories in the released package code.

build: Remove "__fixtures__" and "__mocks__" directories from the released package code

---

src/forms/elements/Step.jsx
src/forms/elements/__stories__/FieldDnbCompany.stories.jsx
src/forms/elements/__stories__/FieldRadios.stories.jsx
src/forms/elements/__stories__/FieldSelect.stories.jsx
src/forms/elements/__stories__/Form.stories.jsx
src/forms/elements/__stories__/Step.stories.jsx
src/forms/elements/__tests__/Step.test.jsx

Change required to match the designs.

fix: Display forms back button as link

---

package.json
src/forms/elements/FieldUneditable.jsx
src/forms/elements/__stories__/FieldUneditable.stories.jsx
src/forms/elements/__tests__/FieldUneditable.test.jsx
yarn.lock

Introduce a new field used to display form values selected in previous form steps.
Depends on https://github.com/uktrade/data-hub-components/pull/151

feat: Add FieldUneditable

---

package.json
src/company-list/DeleteCompanyListSection.jsx
src/company-list/__stories__/DeleteCompanyListSection.stories.jsx
src/company-list/__tests__/DeleteCompanyListSection.test.jsx
yarn.lock

If the XHR request to delete the company list fails, then we need to do something useful. This adds a way to display an error message to the user when this happens.
1. Navigate to DeleteCompanyListSection in Storybook.
1. Have a look at the different stories (a new 'with error' story has been added).

feat: Add ability to display error message to DeleteCompanyListSection

---

src/button-link/ButtonLink.jsx
src/button-link/__tests__/ButtonLink.test.jsx

fix: Make inline variant of ButtonLink to look good on mobile devices

---

src/activity-feed/cards/CompaniesHouseCompany.jsx
src/activity-feed/cards/HmrcExporter.jsx
src/entity-search/EntityList.jsx
src/entity-search/EntityListItem.jsx
src/entity-search/EntityListItemMetaList.jsx
src/entity-search/__tests__/__snapshots__/useDnbSearch.test.jsx.snap
src/entity-search/useDnbSearch.jsx

Using `uniqueId` is bad practice as it regenerates the `key` for each render which leads to performance issues.

refactor: Remove use of uniqueId for key

---

src/status-message/StatusMessage.jsx
src/status-message/__tests__/StatusMessage.test.jsx

This PR adds additional margin-bottom to the `StatusMessage` component.

style: Update spacing of StatusMessage component

---

src/forms/hooks/__tests__/useForm.test.jsx
src/forms/hooks/useForm.js

When typing a field the `values` are set. When deleting the entered text, the field updates but when there is no text it is set to an empty string. Rather than setting to an empty string, the field should be unset.
This became apparent in a bug with D&B company search when the post code was entered, then a user deleted it. An empty string was sent to the API which was invalid and then return a `400`.
Use any of the form stories in Storybook, enter a value in the field and observe the `values` field to see how it changes.

fix: Unset field value if empty string

---

src/forms/elements/FieldDnbCompany.jsx
src/forms/elements/__tests__/FieldDnbCompany.test.jsx
src/forms/elements/__tests__/FieldInput.test.jsx
src/forms/hooks/__tests__/useForm.test.jsx

https://trello.com/c/WxE5JdB3/334-character-limit-on-company-name-search-field-should-be-enforced
Required due to limitation of the DnB service.

fix: Set limit on the company name filter in FieldDnbCompany

---

package.json
src/company-lists/__tests__/CreateListForm.test.jsx
src/forms/elements/FieldInput.jsx
src/forms/elements/__tests__/FieldInput.test.jsx

This PR is removing the additional `label` tag added by`InputField` component.
No visual changes.

fix: Replace InputField with Input component to remove extra label tag

---

src/forms/elements/FieldDnbCompany.jsx
src/forms/elements/__tests__/FieldDnbCompany.test.jsx

D&B service has a requirement of minimum two characters in the search term, this PR is adding a validation rule respecting that limit.

fix: Require two or more characters when searching for D&B companies

---

scripts/setupTests.js
src/forms/hooks/__tests__/useForm.test.jsx
src/forms/hooks/useForm.js

https://trello.com/c/MCKdH7Do/331-when-users-click-next-they-should-start-at-the-top-not-scroll-down
This change will scroll to the top of the page in three conditions:
* When new errors appeared on the form during validation
* When user navigated to the previous step
* When user navigated to the next step

feat: Scroll to top on forms when submitting

---

src/forms/elements/Step.jsx
src/forms/elements/__stories__/FieldDnbCompany.stories.jsx
src/forms/elements/__stories__/Form.stories.jsx
src/forms/elements/__stories__/Step.stories.jsx
src/forms/elements/__tests__/FieldDnbCompany.test.jsx
src/forms/elements/__tests__/Step.test.jsx

**BREAKING CHANGE:** This change is replacing `hideForwardButton`, `hideBackButton`, `forwardButtonText` and `backButtonText` with new `backButton` and `forwardButton` props which now accepts React elements.
**API changes**
`<Step hideForwardButton={true} />` **becomes** `<Step forwardButton={null} />`
`<Step forwardButtonText="Submit form" />` **becomes** `<Step forwardButton="Submit form" />`
New one:
`<Step backButton={<Link href="/companies">Back</Link>} />`

feat: Allow for custom components as back and forward buttons in forms

---

.eslintrc
src/activity-feed/__tests__/Activity.test.jsx
src/activity-feed/__tests__/ActivityFeed.test.jsx
src/activity-feed/cards/HmrcExporter.jsx
src/collection-list/items/ItemMetaWrapper.jsx
src/dashboard/my-companies/useMyCompaniesContext.jsx
src/forms/elements/__tests__/FieldWrapper.test.jsx
src/forms/hooks/useForm.js

**To go in ahead of #189**
To avoid having to check for these formatting issues in the PR stage I've added new eslint rules to restrict empty line to a max of 1, indents to 2 characters and to force a line break at the end of files. 
I've also run `--fix` to remove the errors currently in the codebase. 
This might not all be desirable so is totally open to suggestions.

chore: add new eslint rules for empty lines, indents and EOF line breaks

---

src/collection-list/CollectionHeader.jsx

This is a small refactor to remove the use of SASS syntax in the `CollectionHeader` component in favour of an explicit styled component. There is no visual change. 
This should make the CSS easier to read and understand. 
For consistency, it might be a good idea to refactor the SASS syntax across all components, but this will have to be with the approval of Product & Delivery.

refactor: replace SASS syntax with explicit styled component in CollectionHeader

---

src/forms/elements/FieldDnbCompany.jsx

- Updates CSS for list to be explicit
- Adds extra bullet for help

Update "I cannot find the company I am looking for" list

---

src/collection-list/CollectionDownload.jsx
src/collection-list/__fixtures__/capitalProfileHeading.json
src/collection-list/__stories__/CollectionList.stories.jsx
src/collection-list/__tests__/CollectionDownload.test.jsx

Add `CollectionDownload` component.
The component displays four different things, depending on the number of items passed to it. 
This is the third part of a large piece of work to build out the CollectionList template in React in order to show a list of Large Capital Profiles (and possibly in the future to replace the CollectionList nunjucks macro in the frontend).
With no items:
With 1 item:
With 2 - 5000 items:
With 5001+ items:
The aim is to get to something resembling the below screenshot:

feat: Add CollectionDownload component

---

src/collection-list/CollectionPagination.jsx
src/collection-list/__fixtures__/index.js
src/collection-list/__fixtures__/paginationProps.json
src/collection-list/__stories__/CollectionList.stories.jsx
src/collection-list/__tests__/CollectionPagination.test.jsx

Add `CollectionPagination` component.
The component displays only the previous and next button on mobile view (if passed) and does not render at all if there is only 1 page. (the below screenshot is an exception as I've passed 7 pages to the component in storybook - despite it saying 1 profile).
This is the fourth part of a large piece of work to build out the CollectionList template in React in order to show a list of Large Capital Profiles (and possibly in the future to replace the CollectionList nunjucks macro in the frontend).
Desktop view:
Mobile view:

feat: add CollectionPagination component

---

src/forms/elements/FieldRadios.jsx
src/forms/elements/FieldWrapper.jsx
src/forms/elements/__tests__/FieldRadios.test.jsx
src/forms/elements/__tests__/FieldWrapper.test.jsx

Add ID to the `FieldWrapper` component to make form testing easier, no visual changes.

feat: Add ID to FieldWrapper

---

src/dashboard/my-companies/ListSelector.jsx
src/dashboard/my-companies/MyCompaniesTile.jsx
src/dashboard/my-companies/__tests__/ListSelector.test.jsx
src/dashboard/my-companies/__tests__/MyCompaniesTile.test.jsx

Small style additions to make this more consistent with the section above "Data Hub Updates" section. Header was too large and we were missing the border at the top of the section.

Style to be more inline with the data hub updates section

---

package.json
src/activity-feed/ActivityFeedHeader.jsx
src/address-search/usePostcodeLookup.js
src/collection-list/CollectionDownload.jsx
src/collection-list/CollectionHeader.jsx
src/collection-list/CollectionList.jsx
src/company-lists/DeleteCompanyListSection.jsx
yarn.lock

Replace library used to make plural strings based on a counter.
The new library requires less coding and is used also on the `data-hub-frontend`.

fix: Replace pluralise library with pluralize

---

src/activity-feed/filters/BasicActivityTypeFilter.jsx

in DH there's a global selector `*::after` that sets all the box-sizing to border box, which renders the  output below.

fix: checkbox boxsizing issue

---

src/activity-feed/ActivityFeed.jsx
src/activity-feed/ActivityFeedApp.jsx

currently it's showing the count for all activities coming from the API, we need to display only the count for the activities in view. (This creates confusion when a large number of activities are present)

fix: count only filtered activities

---

src/index.jsx
src/metadata/Metadata.jsx
src/metadata/MetadataItem.jsx
src/metadata/__stories__/Metadata.stories.jsx
src/metadata/__tests__/Metadata.test.jsx

Add component for metadata which will be used on collection pages, activity feed and in a few more places.

feat: Add Metadata component

---

src/index.jsx
src/pagination/Pagination.jsx
src/pagination/__stories__/Pagination.stories.jsx
src/pagination/__tests__/Pagination.test.jsx
src/pagination/computeVisiblePieces.js
src/pagination/constants.js

This component was extracted from the collection list and will replace it in a follow-up PR.

feat: Add Pagination component

---

src/forms/elements/Form.jsx
src/forms/hooks/__tests__/useForm.test.jsx
src/forms/hooks/useForm.js

In some cases we don't want the page to scroll when a form is submitted.

feat: Add an option to choose when a form is scrolling to the top

---

src/dashboard/__stories__/DashboardSection.stories.jsx
src/dashboard/my-companies/MyCompaniesTable.jsx
src/dashboard/my-companies/__tests__/MyCompaniesTable.test.jsx
src/dashboard/my-companies/useMyCompaniesContext.jsx

Users need be able to add an interaction to a company directly from the homepage. I have added an "add interaction" button against each company listed in the company list table, each button will send the user to the "add interaction" flow related to the company.

feat: Add interaction button to table cell

---

src/activity-feed/ActivityFeed.jsx
src/activity-feed/ActivityFeedApp.jsx
src/activity-feed/ActivityFeedFilters.jsx
src/activity-feed/__stories__/ActivityFeed.stories.jsx
src/activity-feed/__tests__/ActivityFeed.test.jsx
src/activity-feed/__tests__/ActivityFeedFilters.test.jsx

fix: Hide the DnB Hierarchical filter when there are no subsidiaries

---

src/collection-list/CollectionItem.jsx
src/collection-list/CollectionList.jsx
src/collection-list/__stories__/CollectionItem.stories.jsx
src/collection-list/__tests__/CollectionItem.test.jsx

Hide `collectionItem` metadata behind details if > 4. Add optional prop `type` to pass to the details summary message. If no `type` prop is passed the message will display 'View details'.

feat: hide collectionItem metadata behind details if > 4

---

src/collection-list/CollectionItem.jsx
src/collection-list/__fixtures__/capitalProfileItem.json
src/collection-list/__fixtures__/capitalProfiles.json
src/collection-list/__fixtures__/interactionItem.json
src/collection-list/__tests__/CollectionItem.test.jsx

Refactor the CollectionItem component to allow it to pass a `border-colour` to the badge component.

feat: allow CollectionItem to pass border-colour to the badge component

---

package.json
src/forms/elements/Form.jsx
src/forms/hooks/__tests__/useForm.test.jsx
src/forms/hooks/useForm.js

Sometimes we might not need the prompt when user exists a form without submitting.

feat: Make the premature form exit prompt configurable

---

src/forms/elements/FieldCheckboxes.jsx
src/forms/elements/FieldDnbCompany.jsx
src/forms/elements/FieldInput.jsx
src/forms/elements/FieldRadios.jsx
src/forms/elements/FieldSelect.jsx
src/forms/elements/__tests__/FieldDnbCompany.test.jsx

Fixes an issue when a company name was truncated when pasted, users then didn't get any results when searching.

fix: Trigger an error if a company name has more than 30 chars within FieldDnbCompany

---

src/typeahead/Typeahead.jsx
src/typeahead/__stories__/Typeahead.stories.jsx
src/typeahead/__tests__/Typeahead.test.jsx
src/typeahead/styles.js

Ads the `error` prop to `Typeahead`, which toggles the red border so its error state is consistent with the rest of `govuk-react` components.

feat: Add error state to Typeahead

---

src/utils/NumberUtils.js
src/utils/__tests__/NumberUtils.test.js

Pass an options object to our currency functions allowing consumers to format currency based on their requirements.
A list of options can be found here:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat

refactor: Add options to currency formatter

---

src/typeahead/Typeahead.jsx

This change fixes a bug in the typeahead component which means if you search in upper case it doesn't return any results. 
This fix makes the query string against the filterOptions lower case. 
You can test this by searching with capital letters in any of the typeahead examples.

Fix upper case bug in typeahead component

---

src/collection-list/CollectionDownload.jsx
src/collection-list/CollectionList.jsx
src/collection-list/__stories__/CollectionList.stories.jsx
src/collection-list/__tests__/CollectionList.test.jsx
src/collection-list/constants.js

Previously, when you had a round ten items on a page you would get a blank additional page. For example, 30 items would result in a blank 4th page. This PR fixes that. 
Also, you can now override the default number of items per page from outside the component by passing the `itemsPerPage` prop. It defaults to `10` if nothing is passed.

fix: fix totalPages bug and allow overriding of itemsPerPage

---

.circleci/config.yml
package.json

This change will allow to use `yalc publish`.

ci: Deploy to GH pages only on CircleCI

---

src/collection-list/CollectionList.jsx
src/collection-list/__tests__/CollectionList.test.jsx

Use the index for the CollectionItem key as the current use of heading and url result in clashing keys in the country specific exportHistory implementation of this component in the frontend.
There isn't a unique id provided for these components, so the next best option is to use the index. This isn't normally advised and hence the `/* eslint-disable react/no-array-index-key */`
This is detailed in the docs here - https://reactjs.org/docs/lists-and-keys.html#keys
I've also added a test for this.

fix: use index for CollectionItem key

---

src/collection-list/CollectionList.jsx
src/collection-list/__tests__/CollectionList.test.jsx

Using the array index for a key may lead to incorrect data being displayed as this might not be unique enough. This PR uses the total items and the active page (along with the index) to generate a key

fix: Ensure key is unique across pages

---

src/collection-list/CollectionList.jsx
src/collection-list/__stories__/CollectionList.stories.jsx
src/collection-list/__tests__/CollectionList.test.jsx
src/pagination/Pagination.jsx

My previous bug fix introduced this small bug. Before when you had 0 results the pagination would render. Now when the `totalPages` === 0 the pagination component won't render.

fix: render no pagination when there are 0 results

---

src/status-message/StatusMessage.jsx

We have been asked by the performance analysis team to add a GA identifier to the 'black box' message that appears on an unmatched company page. In order to do this I need to add a new HTML attribute to it, which is why I am changing the way that the StatusMessage returns.

Change the way StatusMessage returns

---

src/forms/elements/FieldAddress.jsx
src/forms/elements/FieldCheckboxes.jsx
src/forms/elements/FieldDnbCompany.jsx
src/forms/elements/FieldInput.jsx
src/forms/elements/FieldRadios.jsx
src/forms/elements/FieldSelect.jsx
src/forms/elements/FieldUneditable.jsx
src/forms/elements/FieldWrapper.jsx
src/forms/elements/__tests__/FieldWrapper.test.jsx

Hints within form elements often contain links, this PR enables to add them.
(Technically, this is possible now but user will receive a warning due to prop validation).

feat: Allow to pass JSX elements as form hints

---

babel.config.js
package.json
yarn.lock

I've also moved the babel config out to it's own file to match the config structure of the frontend and to make it more discreet.

chore: add optional chaining support to babel config

---

src/forms/elements/FieldTypeahead.jsx
src/forms/elements/__stories__/FieldTypeahead.stories.jsx
src/forms/elements/__tests__/FieldTypeahead.test.jsx
src/index.jsx

Add field wrapper for `Typeahead` component so it can be used in forms.

feat: Add FieldTypeahead

---

src/activity-feed/ActivityFeed.jsx
src/activity-feed/ActivityFeedAction.jsx
src/activity-feed/ActivityFeedApp.jsx
src/activity-feed/ActivityFeedHeader.jsx
src/activity-feed/__stories__/ActivityFeed.stories.jsx
src/activity-feed/__tests__/ActivityFeedAction.test.jsx
src/activity-feed/__tests__/ActivityFeedApp.test.jsx
src/activity-feed/__tests__/ActivityFeedHeader.test.jsx
src/activity-feed/__tests__/__snapshots__/ActivityFeedHeader.test.jsx.snap
src/index.jsx

This PR does 3 things:
1. BREAKING CHANGE: change `contentText` and `contentLink`, which are used to populate the `Add interaction` button, to an array of JSX buttons. These can be defined in the implementation to allow flexibility to add `onClick` functions and the like. I have also provided an example button component called `ActivityFeedButton` which serves our current purposes. 
2. update the styling of the button to give the appropriate borders for desktop and mobile.  
3. refactor ActivityFeedHeader from a class to a functional component. 
In future PRs I am planning to continue to refactor the ActivityFeed to use functional components across all files and to lift the state out so that it can be used with Redux or any other state management.

feat: refactor activityFeed to handle multiple buttons

---

src/new-window-link/NewWindowLink.jsx
src/new-window-link/__tests__/NewWindowLink.test.jsx

This PR makes the help text which shows after a NewWindowLink optional using a 'showHelpText' prop, which defaults to true. It also updates the content of the help text:
Current help text: _(Opens in a new window)_
New help text: (opens in a new window or tab)

fix: update help text for NewWindowLink

---

babel.config.js
package.json
src/forms/elements/FieldDate.jsx
src/forms/elements/__stories__/FieldDate.stories.jsx
src/forms/elements/__tests__/FieldDate.test.jsx
src/forms/hooks/__tests__/useForm.test.jsx
src/forms/hooks/useField.js
src/forms/hooks/useForm.js
yarn.lock

A new date component that allows default and custom validation of dates.

feat: Add date component

---

src/forms/hooks/__tests__/useForm.test.jsx
src/forms/hooks/useForm.js

Fix an edge case where initial value for a field was overriding the values passed with the `Form` component.

fix: Fix setting of initial field value

---

src/typeahead/styles.js

Data Hub front end has a global style which puts a box-shadow on inputs. This means that when the TypeAhead component is used in the front end, there is a yellow outline around the text in the hidden input element. 
This PR overrides this by setting box-shadow to none for the input within the typeahead.
I have made this change in the typeahead component itself, rather than the front end's global styles, as the box shadow may be needed for other input elements in the front end. 
Using [yalc](https://www.npmjs.com/package/yalc) to point the front end repo to this branch 
- Switch to this branch 
- Run `yalc publish `
- In the front end repo run `yalc data-hub-components`
- Go to interactions/create/companyId
- Check that there is no yellow outline on the typeaheads' input text

fix: Override box shadow on Typeahead input text

---

package.json
src/activity-feed/__tests__/__snapshots__/Activity.test.jsx.snap
src/activity-feed/__tests__/__snapshots__/ActivityFeedHeader.test.jsx.snap
src/activity-feed/__tests__/__snapshots__/ActivityFeedPagination.test.jsx.snap
src/activity-feed/activities/card/__tests__/__snapshots__/CardDetails.test.jsx.snap
yarn.lock

Having `styled-components` listed in `dependencies` results in having two `styled-components` instances installed in `data-hub-frontend` which also has it as a dependency:
This then results in this error:
This PR moves `styled-components` to [`peerDependencies`](https://docs.npmjs.com/files/package.json#peerdependencies) which should hopefully solve the problem.

Move styled-components to peer dependencies

---

src/collection-list/CollectionItem.jsx

There was a massive margin above the details so this reduces it

fix: Reduce top margin for details in CollectionItem

---

src/forms/hooks/__tests__/useForm.test.jsx
src/forms/hooks/useForm.js

This PR relates to another PR in the DH front end: https://github.com/uktrade/data-hub-frontend/pull/2672
This PR fixes a bug with the useForm hook, which initially omitted a form field that had been passed an empty string. This would cause the unwanted behaviour of not updating an optional field to an empty string, if a value had been previously submitted or stored on the API. 
The fix is to simply remove the code that would check if the string was empty and omit it. 
Tests have been amended to reflect that we now want to accept an empty string as a value.

fix: Allow setFieldValue to accept empty strings

---

src/forms/elements/FieldDnbCompany.jsx

Steps to reproduce (Add company):
1. Go to dev `/companies/create`
2. Select UK and continue
3. Add a company name such as Lambda and search (yields results)
4. Add any postcode and search again (yields zero results)
5. Clear the postcode field and search again (error HTTP 400)
The problem lies in the existence of an empty postcode field in the body of the POST. The D&B API takes both the company name and the postcode and applies AND Boolean Logic when querying their database. The API errors whenever the postcode is an empty string.
To fix the issue we need to ensure the `postal_code` field is not included in the body of the POST when it's an empty string.

fix: Search DnB companies - only set the postcode if it's defined

---

src/forms/elements/FieldDate.jsx
src/forms/elements/__stories__/FieldDate.stories.jsx
src/forms/elements/__tests__/FieldDate.test.jsx

We would like to add functionality to the FieldDate to only use Month and Year. 
There is a new prop called `format` that you pass for a short date. The default remains the long versions and should not have an impact on components that use the FieldDate.
```jsx
<FieldDate
format="short"
name="date"
label="What is your date of birth?"
hint="For example, 01 09 2019"
required="Enter a valid date of birth"
/>
```

feat: show input based on format

---

src/forms/elements/FieldDate.jsx
src/forms/elements/__tests__/FieldDate.test.jsx
src/utils/DateUtils.js
src/utils/__tests__/DateUtils.test.js

At the moment (no pun intended) the DateFiled only accepts YYYY-MM-DD if a user types in
1-6-2020 for June 1st 2020 it will throw a validation error because it is expects the leading 0.
This PR will normalise date to include the '0' if `n > 10` 
I am aware the moment supports multiple formats however multiple format looks messy 
```js 
moment(dateStr, ['YYYY-MM-DD', 'YYYY-MM-D', 'YYYY-M-D', 'YYYY-M-DD'])
moment(dateStr, ['YYYY-MM', 'YYYY-M'])
``` 
and there is a note on their website 
[Note: Parsing multiple formats is considerably slower than parsing a single format. If you can avoid it, it is much faster to parse a single format.](https://momentjs.com/docs/#/parsing/string-formats/#:~:text=Note:%20Parsing%20multiple%20formats%20is%20considerably%20slower%20than%20parsing%20a%20single%20f …

Normalise date format

---

src/utils/NumberUtils.js
src/utils/__tests__/NumberUtils.test.js

A utility function that allows us to round a `Number` to `n` significant digits. This is helpful when working with larger numbers such as company turnover. For example, a company's turnover is provided in USD from D&B, after the conversion to GBP we can end up with large values such as `2477018007.2000003`. Once this has been rounded to 2 significant figures we end up with `2500000000` allowing the user to edit the value if the D&B estimated turnover is incorrect.

feat: Round a number to n significant digits

---

src/forms/elements/FieldSelect.jsx
src/forms/elements/__tests__/FieldSelect.test.jsx
src/utils/NumberUtils.js
src/utils/__tests__/NumberUtils.test.js

It appears when using React's [recommended](https://reactjs.org/docs/forms.html#the-select-tag) approach to select an option combined with a [govuk-react](https://github.com/govuk-react/govuk-react) [select](https://github.com/govuk-react/govuk-react/tree/master/components/select) we don't get a `selected` attribute on the currently selected option which is causing some FE tests to fail.

fix: select option fix

---

src/forms/elements/FieldWrapper.jsx

This PR simply emboldens form labels to make these React forms more visually consistent with forms across the rest of Data Hub.

Embolden form labels

---

src/forms/elements/FieldDnbCompany.jsx
src/forms/elements/__tests__/FieldDnbCompany.test.jsx

Whilst searching for a DNB company some content changes are needed to be done which will make it clearer to the user when no match is found. See Trello - https://trello.com/c/cBs92dLr/26-move-check-postcode-to-top-of-list-signal-at-the-tips-below-from-the-blue-box

Update content around DNB company search when no matches are found
